name: entrelinhas_app
description: EntreLinhas - frontend Flutter
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  connectivity_plus: ^6.0.3
  
  # Ícones iOS
  cupertino_icons: ^1.0.8

  # Estado (gerenciamento global)
  provider: ^6.0.5

  # HTTP e autenticação segura
  http: ^1.1.0
  flutter_secure_storage: ^8.0.0

  # Armazenamento local (offline sync - RNF06)
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.12

  # Scanner e upload de imagem (RF06, RF11)
  barcode_scan2: ^4.2.0
  image_picker: ^0.8.7+4

  # Fontes e design (tema roxo e dourado)
  google_fonts: ^4.0.3

  # Internacionalização (datas, formatos)
  intl: ^0.18.0

  # Deep Links (para abrir o app via link do e-mail)
  app_links: ^6.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Geração de código para Hive
  hive_generator: ^2.0.0
  build_runner: ^2.4.6

flutter:
  uses-material-design: true

  # Assets (imagens, fontes)
  assets:
    - assets/images/
    - assets/icons/
